CREATE TABLE Preguntas (id_pregunta INTEGER PRIMARY KEY AUTOINCREMENT, pregunta TEXT)
CREATE TABLE Respuestas (id_respuesta INTEGER PRIMARY KEY AUTOINCREMENT, respuesta TEXT, correcta INTEGER, idpregunta INTEGER)
INSERT INTO Preguntas(pregunta) VALUES ("¿En qué ciudad inglesa nació Noel Gallagher?")
INSERT INTO Respuestas(respuesta, correcta, idpregunta) VALUES ("Manchester", 1, 1)
INSERT INTO Respuestas(respuesta, correcta, idpregunta) VALUES ("Liverpool", 0, 1)
INSERT INTO Respuestas(respuesta, correcta, idpregunta) VALUES ("Londres", 0, 1)
INSERT INTO Respuestas(respuesta, correcta, idpregunta) VALUES ("Birmingham", 0, 1)

INSERT INTO Preguntas(pregunta) VALUES ("¿Qué banda de rock fundó Jimmy Page en 1968?")
INSERT INTO Respuestas(respuesta, correcta, idpregunta) VALUES ("Black Sabbath", 0, 2)
INSERT INTO Respuestas(respuesta, correcta, idpregunta) VALUES ("Manfred Mann", 0, 2)
INSERT INTO Respuestas(respuesta, correcta, idpregunta) VALUES ("Led Zeppelin", 1, 2)
INSERT INTO Respuestas(respuesta, correcta, idpregunta) VALUES ("The Who", 0, 2)

INSERT INTO Preguntas(pregunta) VALUES ("¿Cuál de los siguientes cantantes pronunció la frase 'Prefiero que me odien por lo que soy a que me admiren por lo que nunca seré'?")
INSERT INTO Respuestas(respuesta, correcta, idpregunta) VALUES ("Kurt Cobain", 1, 3)
INSERT INTO Respuestas(respuesta, correcta, idpregunta) VALUES ("Jim Morrison", 0, 3)
INSERT INTO Respuestas(respuesta, correcta, idpregunta) VALUES ("John Lennon", 0, 3)
INSERT INTO Respuestas(respuesta, correcta, idpregunta) VALUES ("Freddie Mercury", 0, 3)

INSERT INTO Preguntas(pregunta) VALUES ("¿Como se llama el guitarrista principal de Metallica?")
INSERT INTO Respuestas(respuesta, correcta, idpregunta) VALUES ("Kirk Hammett", 1, 4)
INSERT INTO Respuestas(respuesta, correcta, idpregunta) VALUES ("Joe Satriani", 0, 4)
INSERT INTO Respuestas(respuesta, correcta, idpregunta) VALUES ("Jeff Beck", 0, 4)
INSERT INTO Respuestas(respuesta, correcta, idpregunta) VALUES ("Eddie Van Halen", 0, 4)

INSERT INTO Preguntas(pregunta) VALUES ("¿De que banda es el guitarrista Tom Morello?")
INSERT INTO Respuestas(respuesta, correcta, idpregunta) VALUES ("Deep Purple", 0, 5)
INSERT INTO Respuestas(respuesta, correcta, idpregunta) VALUES ("Rage Against The Machine", 1, 5)
INSERT INTO Respuestas(respuesta, correcta, idpregunta) VALUES ("AC/DC", 0, 5)
INSERT INTO Respuestas(respuesta, correcta, idpregunta) VALUES ("Pink Floyd", 0, 5)

INSERT INTO Preguntas(pregunta) VALUES ("¿Que banda publicó el single November Rain en el año 1991?")
INSERT INTO Respuestas(respuesta, correcta, idpregunta) VALUES ("Deep Purple", 0, 6)
INSERT INTO Respuestas(respuesta, correcta, idpregunta) VALUES ("Guns N' Roses", 1, 6)
INSERT INTO Respuestas(respuesta, correcta, idpregunta) VALUES ("Bon Jovi", 0, 6)
INSERT INTO Respuestas(respuesta, correcta, idpregunta) VALUES ("Oasis", 0, 6)

INSERT INTO Preguntas(pregunta) VALUES ("John Frusciante es guitarrista de la banda...")
INSERT INTO Respuestas(respuesta, correcta, idpregunta) VALUES ("The Killers", 0, 7)
INSERT INTO Respuestas(respuesta, correcta, idpregunta) VALUES ("Guns N' Roses", 0, 7)
INSERT INTO Respuestas(respuesta, correcta, idpregunta) VALUES ("AC/DC", 0, 7)
INSERT INTO Respuestas(respuesta, correcta, idpregunta) VALUES ("Red Hot Chili Peppers", 1, 7)

INSERT INTO Preguntas(pregunta) VALUES ("¿De que país proviene la banda Iron Maiden?")
INSERT INTO Respuestas(respuesta, correcta, idpregunta) VALUES ("EEUU", 0, 8)
INSERT INTO Respuestas(respuesta, correcta, idpregunta) VALUES ("Suecia", 0, 8)
INSERT INTO Respuestas(respuesta, correcta, idpregunta) VALUES ("Reino Unido", 1, 8)
INSERT INTO Respuestas(respuesta, correcta, idpregunta) VALUES ("Alemania", 0, 8)

INSERT INTO Preguntas(pregunta) VALUES ("¿Como se llama la banda formada por los hermanos Gallagher?")
INSERT INTO Respuestas(respuesta, correcta, idpregunta) VALUES ("Motorhead", 0, 9)
INSERT INTO Respuestas(respuesta, correcta, idpregunta) VALUES ("Oasis", 1, 9)
INSERT INTO Respuestas(respuesta, correcta, idpregunta) VALUES ("The Clash", 0, 9)
INSERT INTO Respuestas(respuesta, correcta, idpregunta) VALUES ("Sex Pistols", 0, 9)

INSERT INTO Preguntas(pregunta) VALUES ("¿Cual de estas bandas no está formada en Reino Unido?")
INSERT INTO Respuestas(respuesta, correcta, idpregunta) VALUES ("Judas Priest", 0, 10)
INSERT INTO Respuestas(respuesta, correcta, idpregunta) VALUES ("Motorhead", 0, 10)
INSERT INTO Respuestas(respuesta, correcta, idpregunta) VALUES ("Megadeth", 1, 10)
INSERT INTO Respuestas(respuesta, correcta, idpregunta) VALUES ("Black Sabbath", 0, 10)

INSERT INTO Preguntas(pregunta) VALUES ("¿Que banda formó Dave Mustaine al marcharse de Metallica?")
INSERT INTO Respuestas(respuesta, correcta, idpregunta) VALUES ("Iron Maiden", 0, 11)
INSERT INTO Respuestas(respuesta, correcta, idpregunta) VALUES ("Megadeth", 1, 11)
INSERT INTO Respuestas(respuesta, correcta, idpregunta) VALUES ("Motorhead", 0, 11)
INSERT INTO Respuestas(respuesta, correcta, idpregunta) VALUES ("Pink Floyd", 0, 11)

INSERT INTO Preguntas(pregunta) VALUES ("Steven Tyler es el vocalista de la banda...")
INSERT INTO Respuestas(respuesta, correcta, idpregunta) VALUES ("Green Day", 0, 12)
INSERT INTO Respuestas(respuesta, correcta, idpregunta) VALUES ("Aerosmith", 1, 12)
INSERT INTO Respuestas(respuesta, correcta, idpregunta) VALUES ("Scorpions", 0, 12)
INSERT INTO Respuestas(respuesta, correcta, idpregunta) VALUES ("ZZ top", 0, 12)

INSERT INTO Preguntas(pregunta) VALUES ("¿Que banda publicó en 1976 'Hotel California'?")
INSERT INTO Respuestas(respuesta, correcta, idpregunta) VALUES ("Scorpions", 0, 13)
INSERT INTO Respuestas(respuesta, correcta, idpregunta) VALUES ("Rolling Stones", 0, 13)
INSERT INTO Respuestas(respuesta, correcta, idpregunta) VALUES ("Beattles", 0, 13)
INSERT INTO Respuestas(respuesta, correcta, idpregunta) VALUES ("Eagles", 1, 13)

INSERT INTO Preguntas(pregunta) VALUES ("¿Cual es el disco más vendido de la historia?")
INSERT INTO Respuestas(respuesta, correcta, idpregunta) VALUES ("Thriller - Michael Jackson", 1, 14)
INSERT INTO Respuestas(respuesta, correcta, idpregunta) VALUES ("Back in Black - AC/DC", 0, 14)
INSERT INTO Respuestas(respuesta, correcta, idpregunta) VALUES ("The Dark Side Of The Moon - Pink Floyd", 0, 14)
INSERT INTO Respuestas(respuesta, correcta, idpregunta) VALUES ("Their Greatest Hits - The Eagles", 0, 14)

INSERT INTO Preguntas(pregunta) VALUES ("¿Que album llegó a ser nº1 de las listas britanicas en 1982?")
INSERT INTO Respuestas(respuesta, correcta, idpregunta) VALUES ("The Number of the Beast - Iron Maiden", 1, 15)
INSERT INTO Respuestas(respuesta, correcta, idpregunta) VALUES ("Back in Black - AC/DC", 0, 15)
INSERT INTO Respuestas(respuesta, correcta, idpregunta) VALUES ("Perfect Strangers - Deep Purple", 0, 15)
INSERT INTO Respuestas(respuesta, correcta, idpregunta) VALUES ("Face Dances - The Who", 0, 15)

INSERT INTO Preguntas(pregunta) VALUES ("¿Como se llama el monstruo que tienen por mascota los Iron Maiden?")
INSERT INTO Respuestas(respuesta, correcta, idpregunta) VALUES ("Jack", 0, 16)
INSERT INTO Respuestas(respuesta, correcta, idpregunta) VALUES ("Eddie", 1, 16)
INSERT INTO Respuestas(respuesta, correcta, idpregunta) VALUES ("Steve", 0, 16)
INSERT INTO Respuestas(respuesta, correcta, idpregunta) VALUES ("Paul", 0, 16)

INSERT INTO Preguntas(pregunta) VALUES ("¿London Calling es un single del la banda británica...?")
INSERT INTO Respuestas(respuesta, correcta, idpregunta) VALUES ("Sex Pistols", 0, 17)
INSERT INTO Respuestas(respuesta, correcta, idpregunta) VALUES ("Ramones", 0, 17)
INSERT INTO Respuestas(respuesta, correcta, idpregunta) VALUES ("Joy Division", 0, 17)
INSERT INTO Respuestas(respuesta, correcta, idpregunta) VALUES ("The Clash", 1, 17)

INSERT INTO Preguntas(pregunta) VALUES ("God Save The Queen fué un album censurado en su lanzamiento de la banda...")
INSERT INTO Respuestas(respuesta, correcta, idpregunta) VALUES ("The Damned", 0, 18)
INSERT INTO Respuestas(respuesta, correcta, idpregunta) VALUES ("Sex Pistols", 1, 18)
INSERT INTO Respuestas(respuesta, correcta, idpregunta) VALUES ("Black Flag", 0, 18)
INSERT INTO Respuestas(respuesta, correcta, idpregunta) VALUES ("The Clash", 0, 18)

INSERT INTO Preguntas(pregunta) VALUES ("Numb es una de las canciones más conocidas de...")
INSERT INTO Respuestas(respuesta, correcta, idpregunta) VALUES ("Green Day", 0, 19)
INSERT INTO Respuestas(respuesta, correcta, idpregunta) VALUES ("Linking Park", 1, 19)
INSERT INTO Respuestas(respuesta, correcta, idpregunta) VALUES ("Pearl Jam", 0, 19)
INSERT INTO Respuestas(respuesta, correcta, idpregunta) VALUES ("Blink 182", 0, 19)

INSERT INTO Preguntas(pregunta) VALUES ("¿Como se llama el guitarrista de la banda Pink Floyd?")
INSERT INTO Respuestas(respuesta, correcta, idpregunta) VALUES ("Angus Young", 0, 20)
INSERT INTO Respuestas(respuesta, correcta, idpregunta) VALUES ("Ritchie Blackmore", 0, 20)
INSERT INTO Respuestas(respuesta, correcta, idpregunta) VALUES ("David Gilmour", 1, 20)
INSERT INTO Respuestas(respuesta, correcta, idpregunta) VALUES ("Jimmy Page", 0, 20)
